plugins {
    id 'fabric-loom' version '1.6.1'
    id 'java'
}

sourceSets {
    main {
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    client {
        java {
            srcDirs = ['src/client/java']
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    mappings "net.fabricmc:yarn:1.20.1+build.2"

    modImplementation "net.fabricmc:fabric-loader:0.16.14"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.6+1.20.1"
    
}

loom {
    runConfigs {
        client {
            source sourceSets.client
            client()
        }
    }
}
